---
- include_tasks: storage-facts.yml
  when: vm_facts_generate_storage_facts is defined and vm_facts_generate_storage_facts or vm_facts_generate_backup_facts is defined and vm_facts_generate_backup_facts

- include_tasks: hypervisor-facts.yml
  when: vm_facts_generate_hypervisor_facts is defined and vm_facts_generate_hypervisor_facts
