---
- name: Update repositories cache (apt)
  apt:
    update_cache: yes
  changed_when: false
  when: ansible_pkg_mgr == "apt"

- name: Update repositories cache (pacman)
  pacman:
    update_cache: yes
  changed_when: false
  when: ansible_pkg_mgr == "pacman"

- name: Install python3 (apt)
  apt:
    name: python3
  when: ansible_pkg_mgr == "apt"

- name: Install python3 (pacman)
  pacman:
    name: python
  when: ansible_pkg_mgr == "pacman"